export interface Transaction {
  id: number;
  user: {
    id: number;
    first_name: string;
    last_name: string;
    username: string | null;
    rating: number;
    success_request: number;
    online: boolean;
    avatar_url: string;
  };
  min_deposit: number;
  max_deposit: number;
  amount_receive_from: number;
  amount_receive_to: number;
  amount_commission: number;
  amount_commission_usd: number;
  rate: number;
  bank: {
    id: number;
    slug: string;
    name: string;
    card: string;
    card_fio: string;
    card_bank_name: string;
    is_sbp: number;
    is_erip: number;
    is_refill: number;
    is_withdrawal: number;
    refill_min_amount: number;
    refill_max_amount: number;
    withdrawal_min_amount: number;
    withdrawal_max_amount: number;
    withdrawal_commission: number;
    withdrawal_commission_amount: number;
    additional_percent: number;
    additional_min_amount: number;
    image_url: string;
    type_valid: string;
    is_card_account: number;
    is_card_number: number;
    min_amount_card_account: number;
  };
  average_exchange_time: number;
  currency: {
    id: number;
    title: string;
    code: string;
    fixed: number;
    rate_usd: number;
  };
  room: {
    id: number;
    name: string;
    account: string;
    short_name: string;
    currency: {
      id: number;
      title: string;
      code: string;
      fixed: number;
      rate_usd: number;
    };
    currencies: {
      id: number;
      title: string;
      code: string;
      fixed: number;
      rate_usd: number;
    }[];
    min: number;
    max: number;
    balance_min: number;
    balance_max: number;
    is_balance_exchange: number;
    is_balance_exchange_from: number;
    is_balance_exchange_to: number;
    commission_percent: number;
    commission_amount: number;
    exchange_commission_percent: number;
    exchange_commission_amount: number;
    is_required_verification: boolean;
    contact_type: string;
    percent_rate_deviation: number;
    is_active_express: number;
    express_min: number;
    express_max: number;
    express_min_deposit: number;
    express_max_deposit: number;
  };
  amount_left_usd: number;
  created_at: string;
}
